config/routes.rb
Rails.application.routes.draw do

  get 'home/index'

  root 'home#index'
  get '/auth/:provider/callback', :to => 'sessions#callback'
  post '/auth/:provider/callback', :to => 'sessions#callback'
  resources :categories do
    member do
      get :icon
    end
  end

  resources :stocks do
  end

end

app/models/stock.rb
class Stock < ActiveRecord::Base
	validates :name, 			presence: true
	validates :quantity, 	presence: true
	validates :quantity,  numericality: {greater_than: 0}
	validates :unit, 			presence: true
	belongs_to :category

	accepts_nested_attributes_for :category

	def popular
		self.class.all
	end

	def consumption_of
		case consumption_per
			when 'D'
				value = consumption_count * 30
			when 'W'
				value = consumption_count * 4
			when 'M'
				value = consumption_count
			when 'Y'
				value = consumption_count / 12
		end
		value
	end
	def residual_quantity
		# 更新日と現在日の差日数
		diff = Date.today - updated_at.to_date
		# 一日辺りの減少量
		case consumption_per
			when 'D'
				dec_value = consumption_count
			when 'W'
				dec_value = consumption_count / 7
			when 'M'
				dec_value = consumption_count / 30
			when 'Y'
				dec_value = consumption_count / 365
		end
		value = quantity - (dec_value * diff)
	end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: [:show, :edit, :update, :destroy]

  # GET /stocks
  # GET /stocks.json
  def index
    @stocks = Stock.all
  end

  # GET /stocks/1
  # GET /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
    @stock.build_category
    @popular_stocks = @stock.popular
    @categories = Category.all
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks
  # POST /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to stocks_path, notice: 'Stock was successfully created.' }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1
  # PATCH/PUT /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to stocks_path, notice: 'Stock was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: 'Stock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stock_params
      params.require(:stock).permit(:name, :quantity, :unit, :consumption_per, :consumption_count)
    end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/_form.html.haml
.panel.panel-default
  .panel-heading
    %h3.panel-title=title
  .panel-body
  - if @stock.errors.any?
    .alert.alert-danger
      %ul
      - @stock.errors.full_messages.each do |msg|
        %li= msg
  = form_for @stock, html: { class: 'form-horizontal' } do |f|
    .form-group
      %label.control-label.col-sm-3 カテゴリ
      .col-sm-7
        = f.fields_for :category do |cat|
          - @categories.each_with_index do |cat, i|
            - if i < 4
              .col-xs-3
                %a.thumbnail(data-category-id="#{cat.id}")
                  = image_tag(icon_category_path(cat), class: 'img-thumbnail')
                  %p.category-name= cat.name
            - else
              %a(href="#") その他・・・
    .form-group
      %label.control-label.col-sm-3 名前
      .col-sm-7
        = f.text_field :name, {class: 'form-control', autocomplete: 'off'}
    .form-group
      %label.control-label.col-sm-3 量
      .col-sm-2
        = f.text_field :quantity, {class: 'form-control', autocomplete: 'off'}
      .col-sm-3
        = f.text_field :unit, {class: 'form-control', autocomplete: 'off', placeholder: '単位'}
    .form-group
      %label.control-label.col-sm-3 消費量
      .col-sm-3
        = f.select :consumption_per, {"一日に" => 'D',"一週間に" => 'W',"ひと月に" => 'M', "一年に" => 'Y'}, {}, {class: 'form-control'}
      .col-sm-2
        = f.text_field :consumption_count, {class: 'form-control'}
      .col-sm-2
        %label.control-label.choiced_unit
    .form-group
      .col-sm-offset-3
        = f.submit nil, :class => 'btn btn-primary'
        = link_to t('.cancel', :default => t("helpers.links.cancel")), stocks_path, :class => 'btn'
:javascript
$('.collapse').collapse()

app/views/stocks/edit.html.haml
- model_class = Stock
.row
	.col-md-8.col-md-offset-2
		= render "form", title: "ストックを変更出来ます！"
- content_for :page_javascript do
	= javascript_include_tag "stocks"
- content_for :page_stylesheet do
	= stylesheet_link_tag "stocks"

app/views/stocks/index.html.haml
- model_class = Stock
- unless notice.blank?
  .alert.alert-success
    = notice
.page-header
  %h1 あなたのストック一覧
- unless @stocks.size > 0
  .panel.panel-primary
    .panel-heading
      ストックがありません！
    .panel-body
      = link_to "追加しましょう！", new_stock_path

- else
  %table.table.table-striped
    %thead
      %tr
        %th(style="width: 5%")= model_class.human_attribute_name(:id)
        %th(style="width: 20%")= model_class.human_attribute_name(:name)
        %th(style="width: 20%")= model_class.human_attribute_name(:quantity)
        %th= model_class.human_attribute_name(:created_at)
        %th=t '.actions', :default => t("helpers.actions")
    %tbody
      - @stocks.each do |stock|
        %tr
          %td= link_to stock.id, edit_stock_path(stock)
          %td= stock.name
          %td
            - width = [stock.quantity / stock.consumption_of * 100, 100].min
            .progress
              .progress-bar.progress-bar-striped.active(style="width: #{width}%")
                = "#{stock.residual_quantity} #{stock.unit}"
          %td=l stock.created_at
          %td
            = link_to t('.edit', :default => t("helpers.links.edit")), edit_stock_path(stock), :class => 'btn btn-primary btn-xs'
            = link_to t('.destroy', :default => t("helpers.links.destroy")), stock_path(stock), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger btn-xs'

  = link_to t('.new', :default => t("helpers.links.new")), new_stock_path, :class => 'btn btn-primary'

app/views/stocks/new.html.haml
- model_class = Stock
.row
	= render "form", title: "家の日用品を記録しましょう！"
	- if @popular_stocks.any?
		.panel.panel-primary
			.panel-heading
				みんなはこんなものを記録しています
			.panel-body
				= @popular_stocks
- content_for :page_javascript do
	= javascript_include_tag "stocks"
- content_for :page_stylesheet do
	= stylesheet_link_tag "stocks"

app/views/stocks/show.html.haml
- model_class = Stock
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @stock.name
%p
  %strong= model_class.human_attribute_name(:quantity) + ':'
  %br
  = @stock.quantity
%p
  %strong= model_class.human_attribute_name(:unit) + ':'
  %br
  = @stock.unit

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), stocks_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_stock_path(@stock), :class => 'btn btn-primary'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), stock_path(@stock), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'